import * as path from 'path';
import * as vscode from 'vscode';
import { Finding, parseReportDir } from './core/parser';

export const DIAGNOSTIC_SOURCE = 'graphify-reviewer';

/**
 * Diagnostics Provider.
 *
 * Parses the JSON reports generated by the orchestrator and pushes them
 * into a DiagnosticCollection so findings appear as squiggles in the
 * editor. A file watcher re-parses whenever the reports change on disk
 * (e.g. after a CLI-triggered scan outside VS Code).
 */
export class DiagnosticsProvider implements vscode.Disposable {
  private readonly collection: vscode.DiagnosticCollection;
  private readonly watcher: vscode.FileSystemWatcher;
  private findings: Finding[] = [];

  constructor(private readonly workspaceRoot: string) {
    this.collection = vscode.languages.createDiagnosticCollection(DIAGNOSTIC_SOURCE);
    this.watcher = vscode.workspace.createFileSystemWatcher(
      new vscode.RelativePattern(workspaceRoot, '.scanner-reports/*.json')
    );
    const refresh = () => this.refreshFromDisk();
    this.watcher.onDidCreate(refresh);
    this.watcher.onDidChange(refresh);
    this.watcher.onDidDelete(refresh);
  }

  get currentFindings(): Finding[] {
    return this.findings;
  }

  /** Re-parse reports from disk and update diagnostics. */
  refreshFromDisk(): Finding[] {
    const reportDir = path.join(this.workspaceRoot, '.scanner-reports');
    return this.update(parseReportDir(reportDir).findings);
  }

  /** Update the diagnostic collection from parsed findings. */
  update(findings: Finding[]): Finding[] {
    this.findings = findings;
    this.collection.clear();

    const byFile = new Map<string, vscode.Diagnostic[]>();
    for (const finding of findings) {
      if (!finding.file) {
        continue; // dependency-level findings surface in the tree view/report
      }
      const uri = vscode.Uri.file(path.join(this.workspaceRoot, finding.file));
      const line = Math.max(0, (finding.line ?? 1) - 1);
      const range = new vscode.Range(line, 0, line, Number.MAX_SAFE_INTEGER);
      const diagnostic = new vscode.Diagnostic(
        range,
        finding.message,
        toVsSeverity(finding.severity)
      );
      diagnostic.source = `${DIAGNOSTIC_SOURCE} (${finding.source})`;
      diagnostic.code = finding.rule;

      const key = uri.toString();
      const list = byFile.get(key) ?? [];
      list.push(diagnostic);
      byFile.set(key, list);
    }

    for (const [key, diagnostics] of byFile) {
      this.collection.set(vscode.Uri.parse(key), diagnostics);
    }
    return findings;
  }

  dispose(): void {
    this.watcher.dispose();
    this.collection.dispose();
  }
}

function toVsSeverity(severity: string): vscode.DiagnosticSeverity {
  switch (severity.toUpperCase()) {
    case 'BLOCKER':
    case 'CRITICAL':
      return vscode.DiagnosticSeverity.Error;
    case 'MAJOR':
      return vscode.DiagnosticSeverity.Warning;
    case 'MINOR':
      return vscode.DiagnosticSeverity.Information;
    default:
      return vscode.DiagnosticSeverity.Hint;
  }
}
